services:
  yggdrasil:
    image: alonsojj/yggdrasil:latest
    build: .
    container_name: yggdrasil
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PORT:-8000}:8000"
    # Uncomment if using self-signed certificates
    #volumes:
      # - ./certs:/app/certs